#%RAML 1.0
title: RAML described content management
version: v1
baseUri: http://{host}/api/{version}
types:
  todo: !include schemas/todo.yaml
  todolist: !include schemas/todolist.yaml
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/todolist:
  get:
  /{item_id}:
    get:
    /todo:
      get:
      /{item_id}:
        get:
/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Hello World"
              }
